// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_COLORS_H
#define PICOPIXEL_LVGL_UI_COLORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum ThemesEnum {
    THEME_LIGHT,
    THEME_DARK,
};

enum ThemeColorsEnum {
    THEME_COLOR_BACKGROUND,
    THEME_COLOR_TEXT,
};

extern const char *theme_names[2];
extern uint32_t theme_colors[2][2];
extern uint32_t active_theme_index;
void change_color_theme(uint32_t theme_index);

// Common colors
extern const uint32_t common_b91c1c;
extern const uint32_t common_e63946;
extern const uint32_t common_ffffff;

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_COLORS_H*/
