// Generated by PicoPixel.io — https://picopixel.io
#include "colors.h"

// Common colors
const uint32_t common_030303 = 0x030303;
const uint32_t common_141212 = 0x141212;
const uint32_t common_1a1a1a = 0x1a1a1a;
const uint32_t common_b91c1c = 0xb91c1c;
const uint32_t common_e63946 = 0xe63946;
const uint32_t common_ffffff = 0xffffff;

