// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_COLORS_H
#define PICOPIXEL_LVGL_UI_COLORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Common colors
extern const uint32_t common_030303;
extern const uint32_t common_141212;
extern const uint32_t common_1a1a1a;
extern const uint32_t common_b91c1c;
extern const uint32_t common_e63946;
extern const uint32_t common_ffffff;

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_COLORS_H*/
