// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_IMAGES_H
#define PICOPIXEL_LVGL_UI_IMAGES_H

#include "screens.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifndef EXT_IMG_DESC_T
#define EXT_IMG_DESC_T
typedef struct _ext_img_desc_t {
    const char *name;
    const lv_img_dsc_t *img_dsc;
} ext_img_desc_t;
#endif

extern const lv_img_dsc_t fluent_launcher_settings_28_1e3695;
extern const lv_img_dsc_t fluent_board_games_28_1a71c8;
extern const ext_img_desc_t images[2];


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_IMAGES_H*/
