// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "src/ui/images/fluent_launcher_settings_28_1e3695.inc"
#include "src/ui/images/fluent_board_games_28_1a71c8.inc"
const ext_img_desc_t images[2] = {
    { "fluent_launcher_settings_28_1e3695", &fluent_launcher_settings_28_1e3695 },
    { "fluent_board_games_28_1a71c8", &fluent_board_games_28_1a71c8 }
};
