// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "colors.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;

void create_screen_alarm() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.alarm = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 480, 320);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_e63946), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelalarm
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelalarm = obj;
            lv_obj_set_pos(obj, 121, 112);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "ALARM!\nZum Beenden tippen");
        }
    }

    tick_screen_alarm();
}

void tick_screen_alarm() {
}


void create_screen_settings() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.settings = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 480, 320);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelsettingstitle
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelsettingstitle = obj;
            lv_obj_set_pos(obj, 16, 10);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Einstellungen");
        }
        {
            // labeldauer1caption
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldauer1caption = obj;
            lv_obj_set_pos(obj, 16, 70);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Timer 1");
        }
        {
            // buttondauer1minus
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttondauer1minus = obj;
            lv_obj_set_pos(obj, 140, 60);
            lv_obj_set_size(obj, 44, 44);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttondauer1minus_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttondauer1minus_label = obj;
                    lv_label_set_text(obj, "-5");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // labeldauer1value
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldauer1value = obj;
            lv_obj_set_pos(obj, 196, 70);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "5 min");
        }
        {
            // buttondauer1plus
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttondauer1plus = obj;
            lv_obj_set_pos(obj, 278, 60);
            lv_obj_set_size(obj, 44, 44);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttondauer1plus_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttondauer1plus_label = obj;
                    lv_label_set_text(obj, "+5");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // labeldauer2caption
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldauer2caption = obj;
            lv_obj_set_pos(obj, 16, 140);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Timer 2");
        }
        {
            // buttondauer2minus
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttondauer2minus = obj;
            lv_obj_set_pos(obj, 140, 130);
            lv_obj_set_size(obj, 44, 44);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttondauer2minus_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttondauer2minus_label = obj;
                    lv_label_set_text(obj, "-5");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // labeldauer2value
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldauer2value = obj;
            lv_obj_set_pos(obj, 196, 140);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "15 min");
        }
        {
            // buttondauer2plus
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttondauer2plus = obj;
            lv_obj_set_pos(obj, 278, 130);
            lv_obj_set_size(obj, 44, 44);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttondauer2plus_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttondauer2plus_label = obj;
                    lv_label_set_text(obj, "+5");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // labeldauer3caption
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldauer3caption = obj;
            lv_obj_set_pos(obj, 16, 210);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Timer 3");
        }
        {
            // buttondauer3minus
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttondauer3minus = obj;
            lv_obj_set_pos(obj, 140, 200);
            lv_obj_set_size(obj, 44, 44);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttondauer3minus_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttondauer3minus_label = obj;
                    lv_label_set_text(obj, "-5");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // labeldauer3value
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldauer3value = obj;
            lv_obj_set_pos(obj, 196, 210);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "25 min");
        }
        {
            // buttondauer3plus
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttondauer3plus = obj;
            lv_obj_set_pos(obj, 278, 200);
            lv_obj_set_size(obj, 44, 44);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttondauer3plus_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttondauer3plus_label = obj;
                    lv_label_set_text(obj, "+5");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // buttonsave
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttonsave = obj;
            lv_obj_set_pos(obj, 60, 265);
            lv_obj_set_size(obj, 160, 44);
            lv_obj_set_style_text_letter_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttonsave_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttonsave_label = obj;
                    lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Speichern");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // buttonback
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttonback = obj;
            lv_obj_set_pos(obj, 260, 265);
            lv_obj_set_size(obj, 160, 44);
            lv_obj_set_style_text_letter_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttonback_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttonback_label = obj;
                    lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Zurück");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // labelversion
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelversion = obj;
            lv_obj_set_pos(obj, 406, 10);
            lv_obj_set_size(obj, 61, 21);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "0.1.x");
        }
        {
            // labelip
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelip = obj;
            lv_obj_set_pos(obj, 188, 10);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "192.168.177.102");
        }
        {
            // slidervol
            lv_obj_t *obj = lv_slider_create(parent_obj);
            objects.slidervol = obj;
            lv_obj_set_pos(obj, 276, 143);
            lv_obj_set_size(obj, 200, 20);
            lv_slider_set_range(obj, 0, 100);
            lv_slider_set_value(obj, 50, LV_ANIM_OFF);
            lv_obj_set_style_transform_angle(obj, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // labelvol
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelvol = obj;
            lv_obj_set_pos(obj, 358, 10);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Vol");
        }
    }

    tick_screen_settings();
}

void tick_screen_settings() {
}


void create_screen_home() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.home = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 480, 320);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labeldatum
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeldatum = obj;
            lv_obj_set_pos(obj, 16, 10);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "15.08.2026");
        }
        {
            // labeluhrzeit
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeluhrzeit = obj;
            lv_obj_set_pos(obj, 380, 10);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "14:32");
        }
        {
            // labelcountdown
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelcountdown = obj;
            lv_obj_set_pos(obj, 120, 70);
            lv_obj_set_size(obj, 240, 90);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_700_72_digits_700_72, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "25:00");
        }
        {
            // buttonstart1
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttonstart1 = obj;
            lv_obj_set_pos(obj, 30, 191);
            lv_obj_set_size(obj, 130, 70);
            lv_obj_set_style_text_letter_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttonstart1_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttonstart1_label = obj;
                    lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "5 min");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // buttonstart2
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttonstart2 = obj;
            lv_obj_set_pos(obj, 175, 191);
            lv_obj_set_size(obj, 130, 70);
            lv_obj_set_style_text_letter_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttonstart2_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttonstart2_label = obj;
                    lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "15 min");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // buttonstart3
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttonstart3 = obj;
            lv_obj_set_pos(obj, 320, 191);
            lv_obj_set_size(obj, 130, 70);
            lv_obj_set_style_text_letter_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttonstart3_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttonstart3_label = obj;
                    lv_obj_set_style_text_color(obj, lv_color_hex(common_ffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "25 min");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // buttonsettings
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.buttonsettings = obj;
            lv_obj_set_pos(obj, 30, 280);
            lv_obj_set_size(obj, 28, 28);
            lv_img_set_src(obj, &fluent_launcher_settings_28_1e3695);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
        }
        {
            // buttongame
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.buttongame = obj;
            lv_obj_set_pos(obj, 422, 280);
            lv_obj_set_size(obj, 28, 28);
            lv_img_set_src(obj, &fluent_board_games_28_1a71c8);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
        }
        {
            // buttonstop
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.buttonstop = obj;
            lv_obj_set_pos(obj, 170, 220);
            lv_obj_set_size(obj, 140, 50);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_b91c1c), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_HIDDEN);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // buttonstop_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.buttonstop_label = obj;
                    lv_label_set_text(obj, "Stop");
                    lv_obj_center(obj);
                }
            }
        }
    }

    tick_screen_home();
}

void tick_screen_home() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_alarm,
    tick_screen_settings,
    tick_screen_home,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_alarm() {
    if (objects.alarm != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.alarm);
        lv_obj_del(objects.alarm);
    }
    objects.alarm = 0;
    objects.labelalarm = 0;
}

void delete_screen_settings() {
    if (objects.settings != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.settings);
        lv_obj_del(objects.settings);
    }
    objects.settings = 0;
    objects.labelsettingstitle = 0;
    objects.labeldauer1caption = 0;
    objects.buttondauer1minus = 0;
    objects.buttondauer1minus_label = 0;
    objects.labeldauer1value = 0;
    objects.buttondauer1plus = 0;
    objects.buttondauer1plus_label = 0;
    objects.labeldauer2caption = 0;
    objects.buttondauer2minus = 0;
    objects.buttondauer2minus_label = 0;
    objects.labeldauer2value = 0;
    objects.buttondauer2plus = 0;
    objects.buttondauer2plus_label = 0;
    objects.labeldauer3caption = 0;
    objects.buttondauer3minus = 0;
    objects.buttondauer3minus_label = 0;
    objects.labeldauer3value = 0;
    objects.buttondauer3plus = 0;
    objects.buttondauer3plus_label = 0;
    objects.buttonsave = 0;
    objects.buttonsave_label = 0;
    objects.buttonback = 0;
    objects.buttonback_label = 0;
    objects.labelversion = 0;
    objects.labelip = 0;
    objects.slidervol = 0;
    objects.labelvol = 0;
}

void delete_screen_home() {
    if (objects.home != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.home);
        lv_obj_del(objects.home);
    }
    objects.home = 0;
    objects.labeldatum = 0;
    objects.labeluhrzeit = 0;
    objects.labelcountdown = 0;
    objects.buttonstart1 = 0;
    objects.buttonstart1_label = 0;
    objects.buttonstart2 = 0;
    objects.buttonstart2_label = 0;
    objects.buttonstart3 = 0;
    objects.buttonstart3_label = 0;
    objects.buttonsettings = 0;
    objects.buttongame = 0;
    objects.buttonstop = 0;
    objects.buttonstop_label = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_alarm,
    delete_screen_settings,
    delete_screen_home,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_alarm();
    create_screen_settings();
    create_screen_home();
}
