// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *alarm;
    lv_obj_t *settings;
    lv_obj_t *home;
    lv_obj_t *labeldatum;
    lv_obj_t *labeluhrzeit;
    lv_obj_t *labelcountdown;
    lv_obj_t *buttonstart1;
    lv_obj_t *buttonstart2;
    lv_obj_t *buttonstart3;
    lv_obj_t *buttonsettings;
    lv_obj_t *buttongame;
    lv_obj_t *buttonstop;
    lv_obj_t *labelsettingstitle;
    lv_obj_t *labeldauer1caption;
    lv_obj_t *buttondauer1minus;
    lv_obj_t *labeldauer1value;
    lv_obj_t *buttondauer1plus;
    lv_obj_t *labeldauer2caption;
    lv_obj_t *buttondauer2minus;
    lv_obj_t *labeldauer2value;
    lv_obj_t *buttondauer2plus;
    lv_obj_t *labeldauer3caption;
    lv_obj_t *buttondauer3minus;
    lv_obj_t *labeldauer3value;
    lv_obj_t *buttondauer3plus;
    lv_obj_t *buttonsave;
    lv_obj_t *buttonback;
    lv_obj_t *labelversion;
    lv_obj_t *labelip;
    lv_obj_t *labelalarm;
    lv_obj_t *buttonstart1_label;
    lv_obj_t *buttonstart2_label;
    lv_obj_t *buttonstart3_label;
    lv_obj_t *buttonstop_label;
    lv_obj_t *buttondauer1minus_label;
    lv_obj_t *buttondauer1plus_label;
    lv_obj_t *buttondauer2minus_label;
    lv_obj_t *buttondauer2plus_label;
    lv_obj_t *buttondauer3minus_label;
    lv_obj_t *buttondauer3plus_label;
    lv_obj_t *buttonsave_label;
    lv_obj_t *buttonback_label;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_ALARM = 1,
    SCREEN_ID_SETTINGS = 2,
    SCREEN_ID_HOME = 3,
};

void create_screen_alarm();
void tick_screen_alarm();
void delete_screen_alarm();
void create_screen_settings();
void tick_screen_settings();
void delete_screen_settings();
void create_screen_home();
void tick_screen_home();
void delete_screen_home();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
