// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_FONTS_H
#define PICOPIXEL_LVGL_UI_FONTS_H

#include "../screens.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Custom font declarations (externally visible const structs, no init needed) */
extern const lv_font_t font_montserrat_18;
extern const lv_font_t font_montserrat_22;
extern const lv_font_t font_montserrat_700_72_digits_700_72;

/* Get a custom font by name, returns NULL if not found */
const lv_font_t* ui_get_font_by_name(const char* name);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_FONTS_H*/
