// Generated by PicoPixel.io — https://picopixel.io
/**
 * @file fonts.c
 * @brief Custom font lookup for LVGL UI
 *
 * Each font .c file is compiled separately.
 */

#include "fonts.h"
#include <string.h>

const lv_font_t* ui_get_font_by_name(const char* name) {
    if (name == NULL) return NULL;
    if (strcmp(name, "font_montserrat_18") == 0) return &font_montserrat_18;
    if (strcmp(name, "font_montserrat_22") == 0) return &font_montserrat_22;
    if (strcmp(name, "font_montserrat_700_72_digits_700_72") == 0) return &font_montserrat_700_72_digits_700_72;
    return NULL;
}
